sudo: required

services:
  - docker

language: go

go:
  - 1.x

branches:
  only:
  - master

env:
  global:
    - DOCKERHUB_USERNAME=vadramanenka
    - secure: "YoezX0az9ePp7OQDtHdJnXpSYFfpFUP0aN7XzWbh/oiDMar3PoQLgt3M+NpPtCT2SoGkSVpukYEvxjwJl/Iz3fLBjDYv3MyV5qWZY5h9JDcvF6Fok/xw5wOLIpjghQ1SLqpdlWinMIAwoUWSEqe9SqnrqOVGyYEDVkls3QnjkhpPfZoD/r/zGcUhfiisnBr7/sw/CDLHBc3Qmo1dO/Ksav4ZgHpCXyfD4Evl/TTcrUAUOsu6foMrikNY3q6ztW49zbPe7VNVOQ1uoYWTM/sSKLQCD930+mtLyCpR+51Xe/4nu3+5Ms6UCIYjgUkRC9rYjciGpyvLqFjL4R1kKWKCOWvKdsooEF6Ed0QEePTwEO6PKcjhMHbslAP7SfjsFFmD1bepzal1lNo4BsrmW9W1ptAXXECRv03luXD6ER8lO7u6Kl7YMUuSBwYPoIazfxCG+SCPyH+8d3ux4QuEb4V7zyxt53C5nKHmFUxDiJGDfTFeDtyFXlfBYNT/6MCraZC9mdlVL3eY/8of5K8n8Tp/5euBfSPKSmCY0rwNHF7p0oMcjQxgYeZZnRnrhS38of0ZmrEFj2Ae2SyH+4Hamy8O4C2pq3TuhmbI8g9ziPjuUSajT5VjKY84FoxzJ5cLS1f4xkyKSZNB1GWJBKbXgTV/+AN3s9dkeQvVM8JX8yN1tBM="

install:
  - go get -t -v ./...
  - go install -v github.com/verbumby/verbum

script:
  - go test -v ./...
  - ./docker_build_image.sh

after_success:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD";
      docker push verbumby/web;
    fi
